name: 'warehouse'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

models:
  +persist_docs:
    relation: true
    columns: true
  warehouse:
    marts:
      +materialized: table
      assessments:
        +schema: assessments
      attendance:
        +schema: attendance
      core:
        +schema: core
      enrollment:
        +schema: enrollment
      grades:
        +schema: grades
      row_level_security:
        +schema: row_level_security
    staging:
      +materialized: table
      +schema: staging
