name: 'project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

models:
  +persist_docs:
    relation: true
    columns: true
  project:
    marts:
      +materialized: table
      assessments:
        +schema: assessments
        +tags: edfi
      attendance:
        +schema: attendance
        +tags: edfi
      core:
        +schema: core
        +tags: edfi
      grades:
        +schema: grades
        +tags: edfi
      row_level_security:
        +schema: row_level_security
        +tags: edfi
      surveys:
        +schema: surveys
        # +tags: edfi
    staging:
      +materialized: table
      +schema: staging
      edfi:
        +tags: edfi
        +labels:
            edfi_version: "5_3"

